### ISSUE TITLE
Undeclared dependency on deprecated `babel-eslint`

### ISSUE THREAD

**Issue by simonihmig** [NullVoxPopuli/eslint-configs#327]
When replacing the default eslint config with this (in headless-form) I got this when running `lint:js`:

```
Error: Failed to load parser 'babel-eslint' declared in '.eslintrc.js#overrides[6] » plugin:decorator-position/ember » /Users/sihmig/Projects/oss/ember-headless-form/node_modules/.pnpm/eslint-plugin-decorator-position@5.0.1_eslint@7.32.0/node_modules/eslint-plugin-decorator-position/lib/config/base.js': Cannot find module 'babel-eslint'
Require stack:
- /Users/sihmig/Projects/oss/ember-headless-form/node_modules/.pnpm/eslint-plugin-decorator-position@5.0.1_eslint@7.32.0/node_modules/eslint-plugin-decorator-position/lib/config/base.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:995:15)
    at Function.resolve (node:internal/modules/cjs/helpers:109:19)
    at Object.resolve (/Users/sihmig/Projects/oss/ember-headless-form/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadParser (/Users/sihmig/Projects/oss/ember-headless-form/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:929:45)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/sihmig/Projects/oss/ember-headless-form/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:724:43)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/Users/sihmig/Projects/oss/ember-headless-form/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/Users/sihmig/Projects/oss/ember-headless-form/node_modules/.pnpm/@eslint+eslintrc@0.4.3/node_modules/@eslint/eslintrc/lib/config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
```

Was fixable by installing `babel-eslint`, but if that is required, then it should be declared a peerDependency. However ideally we wouldn't need it at all, since it's replaced by `@babel/eslint-parser`.

**Comment by NullVoxPopuli** [comment]
eslint-plugin-decorator-position caused this! gasp!

I'll fix over there

eslint-configs no longer uses babel-eslint as it's now all ESLint 8 + `@babel/eslint-parser`

**Comment by NullVoxPopuli** [comment]
actually, I can't tell if that's the issue either; https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/search?q=babel-eslint

are `@nullvoxpopuli/eslint-configs` or `eslint-plugin-decorator-position` out of date?

**Comment by simonihmig** [comment]
> are @nullvoxpopuli/eslint-configs or eslint-plugin-decorator-position out of date?

Installed this today, before your recent updates. But eslint-plugin-decorator-position is up to date (in terms of releases, but see below!)

<img width="552" alt="image" src="https://user-images.githubusercontent.com/1325249/212766364-64340f27-f079-4bb9-941b-9dae6abdf57d.png">


> actually, I can't tell if that's the issue either; https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/search?q=babel-eslint

your search is for master, but latest release (`v5.0.1`) still has this: https://github.com/NullVoxPopuli/eslint-plugin-decorator-position/blob/v5.0.1/lib/config/base.js#L11

I guess you just need to cut a release? 😀

**Comment by NullVoxPopuli** [comment]
whoops 😅 I'll get on that. thanks!!

**Comment by NullVoxPopuli** [comment]
5.0.2 released 🙃
